### ISSUE TITLE
Exception after upgrading to Electron 4.0.4

### ISSUE THREAD

**Issue by shpakkdv** [MarshallOfSound/electron-devtools-installer#103]
The same issue like #80 with the latest version of Electron - 4.0.4

UnhandledPromiseRejectionWarning: Error: Version of Electron: 4.0.4 does not match required range ^1.2.1 for extension fmkadmapgofadopljbjfkapdkoienihi
at Object.install (/Users/degtyaru/Downloads/mrc-assy/app/node_modules/electron-devtools-installer/dist/index.js:62:29)
at Promise.all.extensions.map.name (webpack-internal:///578:121:68)
at Array.map ()
at installExtensions (webpack-internal:///578:121:39)
at App.electron_1.app.on (webpack-internal:///578:134:5)
at App.emit (events.js:187:15)

**Comment by MarshallOfSound** [comment]
Update to the latest `electron-devtools-installer`
