### ISSUE TITLE
Unable to install (unzip exits with code 9 "not found")

### ISSUE THREAD

**Issue by nonchip** [MarshallOfSound/electron-devtools-installer#157]
code (from electron-react-boilerplate):

```typescript
//...
  const extensions = ['REACT_DEVELOPER_TOOLS', 'REDUX_DEVTOOLS'];
//...
  extensions.map((name) => installer.default(installer[name], forceDownload))
//...
```

output:

```
Error: Exited with code 9
    at ChildProcess.<anonymous> (/home/kyra/dev/worst_story_engine/node_modules/cross-unzip/index.js:40:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

patched some logging into cross-unzip by hand, it's trying to run:

```
unzip -o ~/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi.crx -d ~/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi
```

looked at that file:

```
$ file ~/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi.crx
~/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi.crx: empty
```

tried to manually remove it, exact same issue again.
looks like somehow instead of e.g. 404ing or similar, the chrome servers just give you an empty file (or you somehow manage to drop the content instead of saving it, but i doubt that, `utils.downloadFile` looks sane), thus not triggering your `Failed to fetch` error.

**Comment by agungsb** [comment]
I also experience this. Probably the culprit `cross-zip` package.

**Comment by agungsb** [comment]
I ended up using https://www.electronjs.org/docs/api/session and it worked fine. Great package anyway 👍

**Comment by esiegel** [comment]
I believe you just need to upgrade to version 3.1.1 which suppports crx version 3 downloads.  It was fixed here: #140

**Comment by andyfaizan** [comment]
@esiegel Thanks! Update to 3.1.1 fixed the issue for me.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
