### ISSUE TITLE
Electron sandbox_bundle.js script failed to run (react-scripts >=5.0.0)

### ISSUE THREAD

**Issue by Rllyyy** [MarshallOfSound/electron-devtools-installer#220]
After upgrading to react-scripts@5.0.0 the following warning appears, when trying to open the the devtools in electron with electron-devtools-installer (`REACT_DEVELOPER_TOOLS`):

```
[1] [20144:0428/213837.341:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[1] [20144:0428/213837.341:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
```

Removing the code associated with electron-devtools-installer fixes the problem.

This error was also documented [here](https://github.com/electron/electron/issues/32133) and [here](https://github.com/electron/electron/issues/33935).

_**Packages:**_
- React: 17.0.2
- Electron: 17.4.0
- electron-devtools-installer: 3.2.0
- react-scripts: 5.0.1

**Comment by shensven** [comment]
+1

**Comment by Nicholaiii** [comment]
This seemingly is independent of the tool installed. Happens for me using vue dev tools.

**Comment by Slapbox** [comment]
@Rllyyy do you see any problems resulting from these errors?

**Comment by Rllyyy** [comment]
The Components and Profiler tab seem to work fine. As does the app itself.
I don't know if this is related but sometimes the console gets spammed with the following message every time some interacts with the websites ui.


```
[10172:0529/223604.786:ERROR:CONSOLE(0)] "Error in event handler: Error: Cannot remove node "517" because no matching node was found in the Store.
[1]     at chrome-extension://hciokebhlhamdchnahfojjpkegfnafpn/build/main.js:25394:43
[1]     at bridge_Bridge.emit (chrome-extension://hciokebhlhamdchnahfojjpkegfnafpn/build/main.js:23500:22)
[1]     at chrome-extension://hciokebhlhamdchnahfojjpkegfnafpn/build/main.js:23660:12
[1]     at listener (chrome-extension://hciokebhlhamdchnahfojjpkegfnafpn/build/main.js:51574:39)", source: chrome-extension://hciokebhlhamdchnahfojjpkegfnafpn/main.html (0)
```

But I can't 100% reproduce it. Might be related to a manual refresh (F5).
Electron continuous to work just fine, but the error also shows up in the Components dev tab.

**Comment by Coldplayer1995** [comment]
I have the same issues with my react version. "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-redux": "^8.0.2",
    "react-router-dom": "5.2.0",

Also it is showing No store found, but obviously there is one.

**Comment by Slapbox** [comment]
@Coldplayer1995 in development or in production? This issue doesn't affect our redux-devtools in development.

**Comment by orpheus** [comment]
Same/similar issue. Getting a light spam of logs even though the `Component` tab works for react-dev-tools.

```
[43019:0610/115709.104244:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[43019:0610/115709.104287:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[43019:0610/115709.212558:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[43019:0610/115709.212758:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[43019:0610/115710.734290:ERROR:CONSOLE(1)] "Extension server error: Object not found: <top>", source: devtools://devtools/bundled/models/extensions/extensions.js (1)
[43019:0610/115718.697043:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[43019:0610/115718.697093:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
```

### Usage
```
import installExtension, {  REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer'

app.whenReady().then(() => {
  installExtension(REACT_DEVELOPER_TOOLS).
    then((name) => console.log(`Added Extension:  ${name}`)).
    catch((err) => console.log('An error occurred: ', err))
})
```

### Versions
Using `electron-forge`

```
... devdeps
    "@electron-forge/cli": "^6.0.0-beta.63",
    "@electron-forge/maker-deb": "^6.0.0-beta.63",
    "@electron-forge/maker-rpm": "^6.0.0-beta.63",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.63",
    "@electron-forge/maker-zip": "^6.0.0-beta.63",
    "@electron-forge/plugin-webpack": "6.0.0-beta.63",
    "electron": "19.0.3",
    "electron-devtools-installer": "^3.2.0",
...deps
    "electron-squirrel-startup": "^1.0.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",

**Comment by Coldplayer1995** [comment]
@Slapbox  I am using reduxjs/toolkit 
 "@reduxjs/toolkit": "^1.8.2",

Added Extension:  React Developer Tools
[32108:0615/105323.045:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[32108:0615/105323.045:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)


Also my store.js
export default configureStore({
    reducer: {
        user: userReducer,
        console: consoleReducer,
        devices: deviceReducer,
        networkInterface: networkInterfaceReducer
    },
    devTools: true,
})
See attached empty state:

![image](https://user-images.githubusercontent.com/26097826/173800196-d384f65b-f772-4701-b061-743aabb4838f.png)

**Comment by Zyles** [comment]
I copy pasted the readme and get same error with VUEJS_DEVTOOLS.

**Comment by BasixKOR** [comment]
We use our custom webpack configuration and can confirm this bug.

**Comment by Coldplayer1995** [comment]
The redux is working but those devtools nope, as you can see I have empty state where in fact the state is not empty :)

**Comment by aaftio** [comment]
`
[5428:0915/205246.655:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[5428:0915/205246.656:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[5428:0915/205256.519:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[5428:0915/205256.525:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
`
I have the same issue.
- "electron": "^20.0.2"
- "electron-devtools-installer": "^3.2.0"
- Windows 11
- Install "REACT_DEVELOPER_TOOLS"
- NodeJS: v16.17.0

**Comment by afbelardi** [comment]
Has anyone found a solution for this error? Still getting the same one

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
