### ISSUE TITLE
using require

### ISSUE THREAD

**Issue by jorfermo** [MarshallOfSound/electron-devtools-installer#24]
How could I use this:

import installExtension, { REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer';

installExtension(REACT_DEVELOPER_TOOLS)
    .then((name) => console.log(`Added Extension:  ${name}`))
    .catch((err) => console.log('An error occurred: ', err));

With node require imports?

**Comment by MarshallOfSound** [comment]
Pretty simply translation.

```js
const electronDevToolsInstaller = require('electron-devtools-installer');

const installExtension = electronDevToolsInstaller.default;
const REACT_DEVELOPER_TOOLS = electronDevToolsInstaller.REACT_DEVELOPER_TOOLS;

installExtension(REACT_DEVELOPER_TOOLS)
    .then((name) => console.log(`Added Extension:  ${name}`))
    .catch((err) => console.log('An error occurred: ', err));
```

Assuming 0 ES6 support in that code block, you can make it look a bit nicer using some ES6 features like destructuring

**Comment by jorfermo** [comment]
That throws this error
```
An error occurred:  TypeError: BrowserWindow.addDevToolsExtension is not a function
  at ./node_modules/electron-devtools-installer/dist/index.js:71:30
  at process._tickCallback (internal/process/next_tick.js:103:7)
  at Module.runMain (module.js:592:11)
  at run (bootstrap_node.js:402:7)
  at startup (bootstrap_node.js:157:9)
  at bootstrap_node.js:521:3
```

**Comment by MarshallOfSound** [comment]
@jorfermo What version of Electron are you using?

**Comment by jorfermo** [comment]
$ ./node_modules/.bin/electron --version
v1.4.1

**Comment by MarshallOfSound** [comment]
@jorfermo With a clean install of electron `1.4.1` and running the code I provided above I get no errors and the execution works as expected.

Are you sure you don't have a global electron install messing something up?

**Comment by jorfermo** [comment]
Not that I'm aware of:

$ electron --version
-bash: electron: command not found

**Comment by MarshallOfSound** [comment]
@jorfermo I have no idea what's going on then.  A clone of `electron-quick-start` and adding this code works perfectly so it must be specific to your app.  Can you provide a minimal reproducible example?

**Comment by jorfermo** [comment]
Sure I just was starting to play a bit with some electron tools. I pasted my main.js

```
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow


const windowStateKeeper = require('electron-window-state');

const isDev = require('electron-is-dev');
if (isDev){
  require('electron-debug')({showDevTools: true});
  require('electron-reload')(__dirname, {
    electron: `${__dirname}/node_modules/.bin/electron`
  });

  const electronDevToolsInstaller = require('electron-devtools-installer');
  const installExtension = electronDevToolsInstaller.default;
  const REACT_DEVELOPER_TOOLS = electronDevToolsInstaller.REACT_DEVELOPER_TOOLS;
  installExtension(REACT_DEVELOPER_TOOLS)
      .then((name) => console.log(`Added Extension:  ${name}`))
      .catch((err) => console.log('An error occurred: ', err));
}

let mainWindow

function createWindow () {
  let mainWindowState = windowStateKeeper({
    defaultWidth: 1000,
    defaultHeight: 800
  });

  mainWindow = new BrowserWindow({
    'x': mainWindowState.x,
    'y': mainWindowState.y,
    'width': mainWindowState.width,
    'height': mainWindowState.height,
    titleBarStyle: 'hidden'
  })
  mainWindowState.manage(mainWindow);
  mainWindow.loadURL(`file://${__dirname}/index.html`)
  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})

```

**Comment by jorfermo** [comment]
Ok, I was calling the methods before the app is ready.

Calling them inside the createWindow function fixed the errors
