### ISSUE TITLE
Failed to fetch extension

### ISSUE THREAD

**Issue by zicjin** [MarshallOfSound/electron-devtools-installer#26]
I have used the proxy tool to ensure that the chrome browser install Vue.js devtools extension fine(with macos SOCKS Proxy). But there is still request timeout for the  Vue.js devtools installation

```
let installExtension = require('electron-devtools-installer')

installExtension.default(installExtension.VUEJS_DEVTOOLS)
    .then((name) => mainWindow.webContents.openDevTools())
    .catch((err) => console.log('An error occurred: ', err))
```

result:
```
...
Failed to fetch extension, trying 0 more times
electron  An error occurred:  { Error: ETIMEDOUT
              at Timeout._onTimeout (/Users/zicjin/Work/pidan/node_modules/request/request.js:759:15)
              at tryOnTimeout (timers.js:232:11)
              at Timer.listOnTimeout (timers.js:202:5) code: 'ETIMEDOUT', connect: false }
```

**Comment by MarshallOfSound** [comment]
Duplicate #25 

Can you ensure you have your PROXY environment variables set correctly 👍
