### ISSUE TITLE
Permission Errors

### ISSUE THREAD

**Issue by bradennapier** [MarshallOfSound/electron-devtools-installer#63]
I tried to reinstall/upgrade the extensions and now I am getting permissions errors... does this need sudo or something!?

```
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/bradennapier/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
    at Function.BrowserWindow.addExtension (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:375:7)
    at Function.BrowserWindow.addDevToolsExtension (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:405:40)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron-devtools-installer/dist/index.js:74:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/bradennapier/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[17:22:47.104] [info] App Finished Startup Procedure
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/bradennapier/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
    at Array.forEach (native)
    at loadDevToolsExtensions (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:285:13)
    at WebContents.<anonymous> (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:296:5)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:191:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/bradennapier/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
connected to remotedev-server
```

The entire thing is broken now and just errors on startup.

**Comment by bradennapier** [comment]
Yeah.... apparently now I suddenly need to use sudo in all cases or things are broken.... including in production

**Comment by jhen0409** [comment]
I've report in https://github.com/facebook/react-devtools/issues/895#issuecomment-331383092, and found Chrome Store modified folder permissions for recently uploaded extensions, it can fix by chmod.

**Comment by lostfictions** [comment]
I'm also having some strange permission errors where I don't have read/write access to the installed extension folder, so I can't `cd` into it and to delete the folder I had to `sudo rm -rf` (definitely unexpected for something that lives in my home folder!)

**Comment by bradennapier** [comment]
I went and recursively set permissions to R&W inside of the package and it fixed the issue for now.

**Comment by alberto2000** [comment]
I had permission error in $home/.config/Electron ... /build/inject.js so I changed that to writable and it solved the issue, not sure how right this feels though
