### ISSUE TITLE
Getting permission error while reading the extension

### ISSUE THREAD

**Issue by neerajdotname** [MarshallOfSound/electron-devtools-installer#66]
1. Getting permission error.
2. Even though I'm getting an error it's being resolved as a `success` and not as an `error`.

```
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/neerajsingh/Library/Application Support/aceinvoice/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
    at Function.BrowserWindow.addExtension (/Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:375:7)
    at Function.BrowserWindow.addDevToolsExtension (/Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:405:40)
    at /Users/neerajsingh/code/aceinvoice-projects/aceinvoice-electron/node_modules/electron-devtools-installer/dist/index.js:75:30
    at <anonymous>
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/neerajsingh/Library/Application Support/aceinvoice/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
Added Extension:  React Developer Tools
```

Here is source code.

```
const electron = require('electron');
const isDev = require('electron-is-dev');
const path = require('path');
const url = require('url');
const R = require('ramda');

const { app, Tray, BrowserWindow, Menu, ipcMain, MenuItem, dialog } = electron;

const attachReactDeveloperTool = () => {
  if (isDev) {
    require('electron-debug')({ enabled: true });
    const {
      default: installExtension,
      REACT_DEVELOPER_TOOLS,
    } = require('electron-devtools-installer');
    installExtension(REACT_DEVELOPER_TOOLS)
      .then(name => console.log(`Added Extension:  ${name}`))
      .catch(err => console.log('An error occurred: ', err));
  }
};

app.on('ready', attachReactDeveloperTool);
```

**Comment by MarshallOfSound** [comment]
This was fixed in a recent release 👍

**Comment by okonet** [comment]
I've just upgraded to version 2.2.13 and still getting 

```
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/okonet/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at readArrayOfFiles (/Users/okonet/Projects/codestage/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/okonet/Projects/codestage/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:33)
    at Array.map (native)
    at injectContentScripts (/Users/okonet/Projects/codestage/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:251:48)
    at loadExtension (/Users/okonet/Projects/codestage/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:280:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/okonet/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
```

**Comment by maxiloEmmmm** [comment]
// get extensions dir path
import { app } from 'electron'
console.log(path.join(app.getPath('userData'), "extensions"))

// rm
rm -fr pathToExtensions
