### ISSUE TITLE
Exception after upgrading to Electron 2.0.0

### ISSUE THREAD

**Issue by brenthompson** [MarshallOfSound/electron-devtools-installer#80]
On latest 2.2.3:

"stack":"Error: Version of Electron: 2.0.0 does not match required range ^1.2.1 for extension fmkadmapgofadopljbjfkapdkoienihi
    at install C:\\Users\\user\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\node_modules\\electron-devtools-installer\\dist\\index.js:62:29)
    at C:\\Users\\user\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\node_modules\\electron-devtools-installer\\dist\\index.js:54:14
    at Array.map (<anonymous>)
    at install (C:\\Users\\user\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\node_modules\\electron-devtools-installer\\dist\\index.js:53:43)

Coming from index.js:
export const REACT_DEVELOPER_TOOLS = {
  id: 'fmkadmapgofadopljbjfkapdkoienihi',
  electron: '^1.2.1',

My project only uses REACT_DEVELOPER_TOOLS and REDUX_DEVTOOLS. I upped those lines to electron: '^2.0.0', and they loaded ok but my devTools locked up several times not long after starting up my app. It runs ok without those tools loaded. I also got lockups just with REDUX_DEVTOOLS, so I'm forced to roll my Electron back to 1.8.6 until this is fixed.

**Comment by Gvozd** [comment]
This workaround worked for me
```js
installExtension(REACT_DEVELOPER_TOOLS.id);
```

**Comment by MarshallOfSound** [comment]
Fixed in `2.2.4`

**Comment by shpakkdv** [comment]
The same issue with the latest version of Electron - 4.0.4

UnhandledPromiseRejectionWarning: Error: Version of Electron: 4.0.4 does not match required range ^1.2.1 for extension fmkadmapgofadopljbjfkapdkoienihi
    at Object.install (/Users/degtyaru/Downloads/mrc-assy/app/node_modules/electron-devtools-installer/dist/index.js:62:29)
    at Promise.all.extensions.map.name (webpack-internal:///578:121:68)
    at Array.map (<anonymous>)
    at installExtensions (webpack-internal:///578:121:39)
    at App.electron_1.app.on (webpack-internal:///578:134:5)
    at App.emit (events.js:187:15)
