### ISSUE TITLE
[Win10] Error: Cannot find module 'babel-plugin-transform-object-rest-spread'

### ISSUE THREAD

**Issue by AoDev** [MarshallOfSound/electron-devtools-installer#87]
version: 2.2.4
OS: Windows 10

Required this way in the app:
```javascript
const {default: installExtension, REACT_DEVELOPER_TOOLS} = require('electron-devtools-installer')
```
Set as `external` in webpack config.

Throws this error when building:
```
Error: Cannot find module 'babel-plugin-transform-object-rest-spread' from EDIT\node_modules\electron-devtools-installer'
    at Function.module.exports [as sync] (EDIT\node_modules\resolve\lib\sync.js:40:15)
    at resolveStandardizedName (EDIT\@babel\core\lib\config\files\plugins.js:78:29)
    at resolvePlugin
```

If I install it, it will require another babel dependency.
It only happens in Windows. In OSX, the build works properly.

Any idea?

**Comment by AoDev** [comment]
I've been investigating this and solved it in a different way. I'll close the issue but if someone reaches this page just be aware that on Windows, some things work differently and can cause this issue.
